import 'package:flutter/material.dart';

/// Named icon → Material icon. The keys are stored verbatim in house.json
/// so this needs to stay stable – add but avoid renaming.
IconData sceneIconFor(String? name) => switch (name) {
      'door' => Icons.door_front_door_outlined,
      'moon' => Icons.nights_stay_outlined,
      'sun' => Icons.wb_sunny_outlined,
      'bed' => Icons.bed_outlined,
      'home' => Icons.home_outlined,
      'star' => Icons.star_border_outlined,
      'movie' => Icons.movie_outlined,
      'book' => Icons.menu_book_outlined,
      'family' => Icons.people_outline,
      'welcome' => Icons.waving_hand_outlined,
      'travel' => Icons.luggage_outlined,
      'power' => Icons.power_settings_new,
      'volume' => Icons.volume_up_outlined,
      'auto' => Icons.settings_suggest_outlined,
      'snow' => Icons.ac_unit,
      'flame' => Icons.local_fire_department_outlined,
      'fan' => Icons.air,
      'drop' => Icons.water_drop_outlined,
      'lamp' => Icons.lightbulb_outline,
      'blinds' => Icons.blinds_outlined,
      'thermo' => Icons.thermostat_outlined,
      'dinner' => Icons.restaurant_outlined,
      'coffee' => Icons.coffee_outlined,
      'music' => Icons.music_note_outlined,
      _ => Icons.auto_awesome_outlined,
    };

/// Stable list of icon names exposed in the scene editor picker.
const kSceneIconPalette = <String>[
  'welcome',
  'door',
  'moon',
  'sun',
  'bed',
  'home',
  'star',
  'movie',
  'book',
  'family',
  'travel',
  'power',
  'volume',
  'auto',
  'snow',
  'flame',
  'fan',
  'drop',
  'lamp',
  'blinds',
  'thermo',
  'dinner',
  'coffee',
  'music',
];
